services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumiere_alajuela
    restart: unless-stopped
    ports:
      - "82:80"
    environment:
      MYSQL_HOST: "db"  # Sigue funcionando internamente con este alias
      MYSQL_USER: "admin_user"
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
      MYSQL_DATABASE: "maindb"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      main_network:
        ipv4_address: 172.19.0.2  # IP estática

  db:
    image: mysql:8.4.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "admin_user"
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
    ports:
      - "3305:3306"
    networks:
      main_network:
        ipv4_address: 172.19.0.3  # IP estática
    volumes:
      - db_data:/var/lib/mysql

networks:
  main_network:
    external: true

volumes:
  db_data:
