services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumiere_alajuela
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: "db" # Ahora apunta al contenedor de MySQL
      MYSQL_USER: "admin_user" # Usuario no root con mismos privilegios
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3" # Contraseña segura
      MYSQL_DATABASE: "maindb" # Cambia esto por el nombre de la base de datos
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - localnet

  db:
    image: mysql:8.4.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1w25GuVZx@R2NESFJppiW3" # Contraseña segura para root
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "admin_user" # Usuario no root con privilegios
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3" # Contraseña segura
    ports:
      - "3305:3306"
    networks:
      - localnet
    volumes:
      - db_data:/var/lib/mysql

networks:
  localnet:
    driver: bridge

volumes:
  db_data:
