services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumiere_alajuela
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: "db"  # Sigue funcionando internamente con este alias
      MYSQL_USER: "admin_user"
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
      MYSQL_DATABASE: "maindb"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      localnet:
        ipv4_address: 192.168.1.100  # IP fija para el contenedor web

  db:
    image: mysql:8.4.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "admin_user"
      MYSQL_PASSWORD: "1w25GuVZx@R2NESFJppiW3"
    ports:
      - "3305:3306"
    networks:
      localnet:
        ipv4_address: 192.168.1.101  # IP fija para MySQL
    volumes:
      - db_data:/var/lib/mysql

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Definimos la subred

volumes:
  db_data:
